{% set version = "0.10.0" %}

package:
  name: build
  version: {{ version }}

source:
  git_url: https://github.com/pypa/build
  git_rev: {{ version }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyproject-build = build.__main__:entrypoint

requirements:
  build:
    - git  # [not win]
  host:
    - python
    - pip
    - wheel
    - flit-core 3.8.0
  run:
    - python
    - packaging >=19.0
    - pyproject_hooks
    - importlib-metadata >=0.22  # [py<38]
    - tomli >=1.1.0  # [py<311]

{% set tests_to_skip = "test_build_wheel or test_build_sdist" %}
{% set tests_to_skip = tests_to_skip + " or test_init" %}  # [linux]
{% set tests_to_skip = tests_to_skip + " or test_output_env_subprocess_error" %}  # [not win]

test:
  source_files:
    - src/build/
    - tests/
  imports:
    - build
    - build.__main__
    - build.env
  requires:
    - pip
    - filelock >=3
    - pytest >=6.2.4
    - pytest-cov >=2.12
    - pytest-mock >=2
    - pytest-rerunfailures >=9.1
    - pytest-xdist >=1.34
    - toml >=0.10.0
    - wheel >=0.36.0
    - setuptools >=42.0.0  # [py<310]
    - setuptools >=56.0.0  # [py>=310]
  commands:
    - pip check
    - pytest ./tests -k "not ({{ tests_to_skip }})"

about:
  home: https://github.com/pypa/build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, correct PEP517 package builder
  description: |
    build is a simple, correct PEP517 package builder. Use with 'python -m build'. This will build the package in an
    isolated environment, generating a source-distribution and wheel in the directory dist/.
  doc_url: https://pypa-build.readthedocs.io
  dev_url: https://github.com/pypa/build

extra:
  recipe-maintainers:
    - FFY00
    - gaborbernat
    - layday
    - henryiii
