{% set version = "0.10.0" %}
{% set sha256 = "d5b71264afdb5951d6704482aac78de887c80691c52b88a9ad195983ca2c9269" %}

package:
  name: build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pyproject-build = build.__main__:entrypoint

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
  run:
    - python >=3.6
    - packaging
    - pep517 >=0.9.1
    - tomli
    - importlib-metadata

test:
  imports:
    - build
    - build.__main__
    - build.env
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pypa/build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, correct PEP517 package builder
  description: |
    build is a simple, correct PEP517 package builder. Use with 'python -m build'. This will build the package in an isolated environment, generating a source-distribution and wheel in the directory dist/.
  doc_url: https://pypa-build.readthedocs.io/en/latest/
  dev_url: https://github.com/pypa/build

extra:
  recipe-maintainers:
    - jasongrout
    - FFY00
    - gaborbernat
