{% set version = "0.10.0" %}
{% set sha256 = "d5b71264afdb5951d6704482aac78de887c80691c52b88a9ad195983ca2c9269" %}

package:
  name: build
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/build/build-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyproject-build = build.__main__:entrypoint

requirements:
  host:
    - python
    - pip
    - wheel
    - flit-core 3.8.0
  run:
    - python
    - packaging >=19.0
    - pyproject_hooks
    - importlib-metadata >=0.22  # [py<38]
    - tomli >=1.1.0  # [py<311]

test:
  imports:
    - build
    - build.__main__
    - build.env
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pypa/build
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple, correct PEP517 package builder
  description: |
    build is a simple, correct PEP517 package builder. Use with 'python -m build'. This will build the package in an
    isolated environment, generating a source-distribution and wheel in the directory dist/.
  doc_url: https://pypa-build.readthedocs.io
  dev_url: https://github.com/pypa/build

extra:
  recipe-maintainers:
    - FFY00
    - gaborbernat
    - layday
    - henryiii
